# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 805a059f546879e8d70b907e8f3ae53030048e5d844de8fe1bb9d6ca55f53f51dc498ae88cc2e4f2c4b25203f72ee1780db8183172f729b59989af99f1356f9b

test:
  secret_key_base: c922cf8e059a05662045f7fdde1f617ae7289df7497f5fa636965f6c7bbb26789f55e03bae8d84734ffe1e12f77a78152299e2fd5fcd2efc85e6eba636c94ec8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
